//! Read-only bundled calendar event data. Ported from `CalendarEventStore.swift`.
//!
//! The JSON is embedded at compile time so festival lookup works offline and
//! needs no filesystem at runtime.

use std::collections::BTreeMap;

use serde::{Deserialize, Serialize};

use crate::config::Pack;
use crate::config::calendar::CalendarPack;
use crate::config::calendar_years::CalendarYearsPack;
use crate::numerals::to_ascii_digits;

/// Festival and tithi coverage in the bundled data. Years outside this range are
/// intentionally unavailable: their source files had no festival or tithi
/// information beyond the Saturday flags the calendar already derives.
pub const FIRST_EVENT_YEAR: i32 = 2066;
pub const LAST_EVENT_YEAR: i32 = 2083;

/// The last year with festival data: the bundled range, extended by any
/// later years the `calendar-years` pack carries.
pub fn last_event_year() -> i32 {
    CalendarYearsPack::active()
        .last_year()
        .map_or(LAST_EVENT_YEAR, |year| year.max(LAST_EVENT_YEAR))
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct CalendarEvent {
    pub name: Option<String>,
    pub tithi: Option<String>,
    pub is_public_holiday: bool,
    /// An auspicious day (saait) for a wedding, per the official calendar.
    #[serde(default)]
    pub marriage: bool,
    /// An auspicious day for a bratabandha.
    #[serde(default)]
    pub bratabandha: bool,
}

/// One month as the source almanac files write it — the bundled files and
/// the `calendar-years` pack share this shape.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct MonthPayload {
    pub days: Vec<SourceDay>,
    /// The month's saait, as the almanac prints it: "९, १०, १६ र २६ गते",
    /// or a sentence saying there is none.
    #[serde(default)]
    pub marriage: Vec<String>,
    #[serde(default)]
    pub bratabandha: Vec<String>,
}

/// The days of the month a saait line names. Every form in the bundled data
/// is either a list of day numbers or a sentence with none in it, so the
/// numbers are all there is to read.
fn saait_days(lines: &[String]) -> Vec<u32> {
    lines
        .iter()
        .flat_map(|line| {
            line.split(|c: char| !c.is_numeric())
                .filter_map(|part| to_ascii_digits(part).parse::<u32>().ok())
                .collect::<Vec<_>>()
        })
        .filter(|day| (1..=32).contains(day))
        .collect()
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct SourceDay {
    /// The BS day in Devanagari; empty for the previous month's trailing days.
    #[serde(rename = "n")]
    pub nepali_day: String,
    #[serde(rename = "t", default)]
    pub tithi: String,
    #[serde(rename = "f", default)]
    pub festival: String,
    #[serde(rename = "h", default)]
    pub is_holiday: bool,
}

// One entry per (year, month) of bundled JSON. Generated by `build.rs`.
include!(concat!(env!("OUT_DIR"), "/events_data.rs"));

fn raw_month(year: i32, month: u32) -> Option<&'static str> {
    if !(FIRST_EVENT_YEAR..=LAST_EVENT_YEAR).contains(&year) || !(1..=12).contains(&month) {
        return None;
    }
    let index = (year - FIRST_EVENT_YEAR) as usize * 12 + (month - 1) as usize;
    EVENT_FILES.get(index).copied().flatten()
}

/// Events for a BS month, keyed by day of month, with the active calendar
/// pack's corrections laid over the bundled data. Missing or unparseable
/// data yields an empty map rather than an error — the calendar still
/// renders.
pub fn events(year: i32, month: u32) -> BTreeMap<u32, CalendarEvent> {
    let mut result = bundled_events(year, month);
    for patch in CalendarPack::active().patches(year, month) {
        let event = result.entry(patch.day).or_insert_with(|| CalendarEvent {
            name: None,
            tithi: None,
            is_public_holiday: false,
            marriage: false,
            bratabandha: false,
        });
        let cleared = |text: &String| {
            let text = text.trim();
            (!text.is_empty()).then(|| text.to_owned())
        };
        if let Some(name) = &patch.name {
            event.name = cleared(name);
        }
        if let Some(tithi) = &patch.tithi {
            event.tithi = cleared(tithi);
        }
        if let Some(holiday) = patch.holiday {
            event.is_public_holiday = holiday;
        }
    }
    result
}

/// The bundled events, or the `calendar-years` pack's for a later year.
fn bundled_events(year: i32, month: u32) -> BTreeMap<u32, CalendarEvent> {
    if let Some(raw) = raw_month(year, month) {
        return serde_json::from_str::<MonthPayload>(raw)
            .map(month_events)
            .unwrap_or_default();
    }
    if year > LAST_EVENT_YEAR
        && let Some(payload) = CalendarYearsPack::active().month(year, month)
    {
        return month_events(payload.clone());
    }
    BTreeMap::new()
}

/// A source month's days, keyed by day of month.
fn month_events(payload: MonthPayload) -> BTreeMap<u32, CalendarEvent> {
    let marriage = saait_days(&payload.marriage);
    let bratabandha = saait_days(&payload.bratabandha);
    let mut result = BTreeMap::new();
    // Source months open with trailing days of the previous month; skip until
    // day 1 appears so those never overwrite this month's entries.
    let mut reached_first_day = false;
    for source in payload.days {
        let Ok(day) = to_ascii_digits(&source.nepali_day).parse::<u32>() else {
            continue;
        };
        if day == 1 {
            reached_first_day = true;
        }
        if !reached_first_day {
            continue;
        }

        let name = source.festival.trim();
        let tithi = source.tithi.trim();
        result.insert(
            day,
            CalendarEvent {
                name: (!name.is_empty()).then(|| name.to_owned()),
                tithi: (!tithi.is_empty()).then(|| tithi.to_owned()),
                is_public_holiday: source.is_holiday,
                marriage: marriage.contains(&day),
                bratabandha: bratabandha.contains(&day),
            },
        );
    }
    result
}

#[cfg(test)]
mod tests {
    use super::*;

    fn lines(text: &str) -> Vec<String> {
        vec![text.to_owned()]
    }

    #[test]
    fn reads_the_days_a_saait_line_names() {
        assert_eq!(
            saait_days(&lines("९, १०, १६, १७, १९, २४, २५ र  २६ गते")),
            [9, 10, 16, 17, 19, 24, 25, 26]
        );
        assert_eq!(saait_days(&lines("३ ,७ र १२  गते")), [3, 7, 12]);
        assert!(saait_days(&lines("यो महिना को लागी विवाह मुर्हुत छैन ।")).is_empty());
    }

    /// Mangsir 2083 has weddings on the 9th and none for a bratabandha.
    #[test]
    fn marks_the_bundled_saait_on_its_days() {
        let month = events(2083, 8);
        assert!(month[&9].marriage);
        assert!(!month[&8].marriage);
        assert!(month.values().all(|day| !day.bratabandha));
    }
}
