//! Read-only bundled calendar event data. Ported from `CalendarEventStore.swift`.
//!
//! The JSON is embedded at compile time so festival lookup works offline and
//! needs no filesystem at runtime.

use std::collections::BTreeMap;

use serde::{Deserialize, Serialize};

use crate::numerals::to_ascii_digits;

/// Festival and tithi coverage in the bundled data. Years outside this range are
/// intentionally unavailable: their source files had no festival or tithi
/// information beyond the Saturday flags the calendar already derives.
pub const FIRST_EVENT_YEAR: i32 = 2066;
pub const LAST_EVENT_YEAR: i32 = 2083;

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct CalendarEvent {
    pub name: Option<String>,
    pub tithi: Option<String>,
    pub is_public_holiday: bool,
}

#[derive(Deserialize)]
struct MonthPayload {
    days: Vec<SourceDay>,
}

#[derive(Deserialize)]
struct SourceDay {
    #[serde(rename = "n")]
    nepali_day: String,
    #[serde(rename = "t", default)]
    tithi: String,
    #[serde(rename = "f", default)]
    festival: String,
    #[serde(rename = "h", default)]
    is_holiday: bool,
}

// One entry per (year, month) of bundled JSON. Generated by `build.rs`.
include!(concat!(env!("OUT_DIR"), "/events_data.rs"));

fn raw_month(year: i32, month: u32) -> Option<&'static str> {
    if !(FIRST_EVENT_YEAR..=LAST_EVENT_YEAR).contains(&year) || !(1..=12).contains(&month) {
        return None;
    }
    let index = (year - FIRST_EVENT_YEAR) as usize * 12 + (month - 1) as usize;
    EVENT_FILES.get(index).copied().flatten()
}

/// Events for a BS month, keyed by day of month. Missing or unparseable data
/// yields an empty map rather than an error — the calendar still renders.
pub fn events(year: i32, month: u32) -> BTreeMap<u32, CalendarEvent> {
    let Some(raw) = raw_month(year, month) else {
        return BTreeMap::new();
    };
    let Ok(payload) = serde_json::from_str::<MonthPayload>(raw) else {
        return BTreeMap::new();
    };

    let mut result = BTreeMap::new();
    // Source months open with trailing days of the previous month; skip until
    // day 1 appears so those never overwrite this month's entries.
    let mut reached_first_day = false;
    for source in payload.days {
        let Ok(day) = to_ascii_digits(&source.nepali_day).parse::<u32>() else {
            continue;
        };
        if day == 1 {
            reached_first_day = true;
        }
        if !reached_first_day {
            continue;
        }

        let name = source.festival.trim();
        let tithi = source.tithi.trim();
        result.insert(
            day,
            CalendarEvent {
                name: (!name.is_empty()).then(|| name.to_owned()),
                tithi: (!tithi.is_empty()).then(|| tithi.to_owned()),
                is_public_holiday: source.is_holiday,
            },
        );
    }
    result
}
