//! Read-only bundled calendar event data. Ported from `CalendarEventStore.swift`.
//!
//! The JSON is embedded at compile time so festival lookup works offline and
//! needs no filesystem at runtime.

use std::collections::BTreeMap;

use serde::{Deserialize, Serialize};

use crate::numerals::to_ascii_digits;

/// Festival and tithi coverage in the bundled data. Years outside this range are
/// intentionally unavailable: their source files had no festival or tithi
/// information beyond the Saturday flags the calendar already derives.
pub const FIRST_EVENT_YEAR: i32 = 2066;
pub const LAST_EVENT_YEAR: i32 = 2083;

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct CalendarEvent {
    pub name: Option<String>,
    pub tithi: Option<String>,
    pub is_public_holiday: bool,
    /// An auspicious day (saait) for a wedding, per the official calendar.
    #[serde(default)]
    pub marriage: bool,
    /// An auspicious day for a bratabandha.
    #[serde(default)]
    pub bratabandha: bool,
}

#[derive(Deserialize)]
struct MonthPayload {
    days: Vec<SourceDay>,
    /// The month's saait, as the almanac prints it: "९, १०, १६ र २६ गते",
    /// or a sentence saying there is none.
    #[serde(default)]
    marriage: Vec<String>,
    #[serde(default)]
    bratabandha: Vec<String>,
}

/// The days of the month a saait line names. Every form in the bundled data
/// is either a list of day numbers or a sentence with none in it, so the
/// numbers are all there is to read.
fn saait_days(lines: &[String]) -> Vec<u32> {
    lines
        .iter()
        .flat_map(|line| {
            line.split(|c: char| !c.is_numeric())
                .filter_map(|part| to_ascii_digits(part).parse::<u32>().ok())
                .collect::<Vec<_>>()
        })
        .filter(|day| (1..=32).contains(day))
        .collect()
}

#[derive(Deserialize)]
struct SourceDay {
    #[serde(rename = "n")]
    nepali_day: String,
    #[serde(rename = "t", default)]
    tithi: String,
    #[serde(rename = "f", default)]
    festival: String,
    #[serde(rename = "h", default)]
    is_holiday: bool,
}

// One entry per (year, month) of bundled JSON. Generated by `build.rs`.
include!(concat!(env!("OUT_DIR"), "/events_data.rs"));

fn raw_month(year: i32, month: u32) -> Option<&'static str> {
    if !(FIRST_EVENT_YEAR..=LAST_EVENT_YEAR).contains(&year) || !(1..=12).contains(&month) {
        return None;
    }
    let index = (year - FIRST_EVENT_YEAR) as usize * 12 + (month - 1) as usize;
    EVENT_FILES.get(index).copied().flatten()
}

/// Events for a BS month, keyed by day of month. Missing or unparseable data
/// yields an empty map rather than an error — the calendar still renders.
pub fn events(year: i32, month: u32) -> BTreeMap<u32, CalendarEvent> {
    let Some(raw) = raw_month(year, month) else {
        return BTreeMap::new();
    };
    let Ok(payload) = serde_json::from_str::<MonthPayload>(raw) else {
        return BTreeMap::new();
    };

    let marriage = saait_days(&payload.marriage);
    let bratabandha = saait_days(&payload.bratabandha);
    let mut result = BTreeMap::new();
    // Source months open with trailing days of the previous month; skip until
    // day 1 appears so those never overwrite this month's entries.
    let mut reached_first_day = false;
    for source in payload.days {
        let Ok(day) = to_ascii_digits(&source.nepali_day).parse::<u32>() else {
            continue;
        };
        if day == 1 {
            reached_first_day = true;
        }
        if !reached_first_day {
            continue;
        }

        let name = source.festival.trim();
        let tithi = source.tithi.trim();
        result.insert(
            day,
            CalendarEvent {
                name: (!name.is_empty()).then(|| name.to_owned()),
                tithi: (!tithi.is_empty()).then(|| tithi.to_owned()),
                is_public_holiday: source.is_holiday,
                marriage: marriage.contains(&day),
                bratabandha: bratabandha.contains(&day),
            },
        );
    }
    result
}

#[cfg(test)]
mod tests {
    use super::*;

    fn lines(text: &str) -> Vec<String> {
        vec![text.to_owned()]
    }

    #[test]
    fn reads_the_days_a_saait_line_names() {
        assert_eq!(
            saait_days(&lines("९, १०, १६, १७, १९, २४, २५ र  २६ गते")),
            [9, 10, 16, 17, 19, 24, 25, 26]
        );
        assert_eq!(saait_days(&lines("३ ,७ र १२  गते")), [3, 7, 12]);
        assert!(saait_days(&lines("यो महिना को लागी विवाह मुर्हुत छैन ।")).is_empty());
    }

    /// Mangsir 2083 has weddings on the 9th and none for a bratabandha.
    #[test]
    fn marks_the_bundled_saait_on_its_days() {
        let month = events(2083, 8);
        assert!(month[&9].marriage);
        assert!(!month[&8].marriage);
        assert!(month.values().all(|day| !day.bratabandha));
    }
}
