// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AirQuality = { 
/**
 * The US AQI scale, which is what Nepali outlets quote.
 */
usAqi: number, pm25: number, pm10: number, observedAt: string, };
