// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AnnouncementAction } from "./AnnouncementAction";
import type { AnnouncementLevel } from "./AnnouncementLevel";
import type { AnnouncementPlatform } from "./AnnouncementPlatform";
import type { LocalizedText } from "./LocalizedText";

export type Announcement = { id: string, level: AnnouncementLevel, title: LocalizedText, body: LocalizedText, startsAt: string | null, expiresAt: string | null, action: AnnouncementAction | null, 
/**
 * Empty means every platform.
 */
platforms: Array<AnnouncementPlatform>, };
