// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Announcement } from "./Announcement";

/**
 * Notices published through the signed config channel rather than the
 * announcements Worker: free to serve, and changed only by a PR.
 */
export type AnnouncementsPack = { notices: Array<Announcement>, };
