// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Announcement } from "./Announcement";

/**
 * A wrapper instead of HTTP 204 lets Sajilo cache the deliberate absence
 * of a notice. Otherwise an expired banner would remain visible until the
 * app restarted or its previous cache entry aged out.
 */
export type AnnouncementResponse = { announcement: Announcement | null, };
