// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How an announcement arrives.
 */
export type AnnouncementDelivery = "quiet" | "popup";
