// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What an announcement is about. Each kind has its own switch in
 * Settings › Notifications › From Sajilo.
 */
export type AnnouncementCategory = "notice" | "greeting" | "update" | "status" | "tip" | "ask" | "general";
