// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Announcement } from "./Announcement";

/**
 * The notices live now, most pressing first. A wrapper, not HTTP 204, so
 * Sajilo caches the deliberate absence of notices too; otherwise an
 * expired one would linger until its cache entry aged out.
 *
 * The Worker also sends a single `announcement` field, which this type
 * ignores: it is what versions before the list read, and it carries a
 * standing "update Sajilo" notice for them.
 */
export type AnnouncementResponse = { announcements: Array<Announcement>, };
