// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which desktop a notice is for. Matched on the device: the app never
 * says which platform it runs on.
 */
export type AnnouncementPlatform = "windows" | "macos" | "linux";
