// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One company's declared dividend. The book closure is the date that
 * matters to a holder: whoever holds the share on it receives the payout.
 */
export type BookClosure = { symbol: string, companyName: string, 
/**
 * Bonus shares, as a percent of the holding.
 */
bonusPercent: number, 
/**
 * Cash, as a percent of face value.
 */
cashPercent: number, 
/**
 * ISO `YYYY-MM-DD`, a Nepal calendar day.
 */
bookClosureDate: string, 
/**
 * e.g. `2082/2083`.
 */
fiscalYear: string | null, };
