// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModuleKey } from "./ModuleKey";

/**
 * What a client is asking for. An empty `modules` means "all of them".
 */
export type BundleRequest = { modules: Array<ModuleKey>, 
/**
 * Weather is fetched per place (a `sajilo_core::places` id), so the
 * server only warms the ones clients actually ask for. The wire name
 * predates the place list; its values (`"kathmandu"`) are unchanged.
 */
weatherLocation: string | null, };
