// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ForexSnapshot } from "./ForexSnapshot";
import type { FuelPriceSnapshot } from "./FuelPriceSnapshot";
import type { LoadState } from "./LoadState";
import type { MetalRateSnapshot } from "./MetalRateSnapshot";
import type { NewsDigest } from "./NewsDigest";
import type { RadioDirectory } from "./RadioDirectory";
import type { RashifalSnapshot } from "./RashifalSnapshot";
import type { VegetableMarketSnapshot } from "./VegetableMarketSnapshot";
import type { WeatherSnapshot } from "./WeatherSnapshot";

/**
 * Only the requested modules are populated; the rest stay `None` so a
 * client can tell "not asked for" from "asked for and unavailable".
 */
export type BundleResponse = { weather: LoadState<WeatherSnapshot> | null, forex: LoadState<ForexSnapshot> | null, news: LoadState<NewsDigest> | null, metals: LoadState<MetalRateSnapshot> | null, fuel: LoadState<FuelPriceSnapshot> | null, vegetables: LoadState<VegetableMarketSnapshot> | null, rashifal: LoadState<RashifalSnapshot> | null, radio: LoadState<RadioDirectory> | null, };
