// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModuleKey } from "./ModuleKey";
import type { WeatherLocation } from "./WeatherLocation";

/**
 * What a client is asking for. An empty `modules` means "all of them".
 */
export type BundleRequest = { modules: Array<ModuleKey>, 
/**
 * Weather is fetched per city, so the server only warms the ones
 * clients actually ask for.
 */
weatherLocation: WeatherLocation | null, };
