// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContactCategory } from "./ContactCategory";
import type { ContactTone } from "./ContactTone";

export type Contact = { name: string, nameNe: string, number: string, description: string, descriptionNe: string, category: ContactCategory, tone: ContactTone, };
