// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A coin found by name or ticker across every coin the source knows,
 * not only the ones in the market list. Opening one asks for its prices.
 */
export type CryptoSearchHit = { id: string, 
/**
 * Ticker, upper case: `PEPE`.
 */
symbol: string, name: string, 
/**
 * Position by market value; `None` for coins too small to rank.
 */
rank: number | null, imageUrl: string | null, };
