// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CryptoCoin } from "./CryptoCoin";
import type { Freshness } from "./Freshness";

export type CryptoSnapshot = { coins: Array<CryptoCoin>, source: string, freshness: Freshness, };
