// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One point on a price chart: Unix seconds and US dollars. Seconds fit
 * a `u32` until 2106, and keep the TypeScript side a plain number.
 */
export type CryptoPricePoint = { time: number, price: number, };
