// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One coin as the market list shows it, most prominent first.
 */
export type CryptoCoin = { 
/**
 * The source's stable id, used to ask for this coin's chart.
 */
id: string, 
/**
 * Ticker, upper case: `BTC`.
 */
symbol: string, name: string, imageUrl: string | null, 
/**
 * Position by market value; `None` where the source gives none.
 */
rank: number | null, 
/**
 * US dollars.
 */
price: number, 
/**
 * Percent over the last 24 hours and 7 days.
 */
change24h: number | null, change7d: number | null, marketCap: number | null, 
/**
 * US dollars traded in the last 24 hours.
 */
volume24h: number | null, high24h: number | null, low24h: number | null, circulatingSupply: number | null, maxSupply: number | null, 
/**
 * All-time high, how far below it the price is (percent, negative),
 * and when it was reached (ISO date).
 */
allTimeHigh: number | null, fromAllTimeHigh: number | null, allTimeHighDate: string | null, 
/**
 * Hourly prices over the last 7 days, oldest first; empty where the
 * source has none.
 */
sparkline: Array<number>, };
