// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CryptoPricePoint } from "./CryptoPricePoint";
import type { Freshness } from "./Freshness";

/**
 * A coin's price over a span of days.
 */
export type CryptoChart = { id: string, days: number, points: Array<CryptoPricePoint>, source: string, freshness: Freshness, };
