// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WeatherCondition } from "./WeatherCondition";

export type DailyForecast = { date: string, highCelsius: number, lowCelsius: number, condition: WeatherCondition, 
/**
 * Chance of precipitation, 0–100.
 */
precipitationChance: number, };
