// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How precisely `published` is known.
 *
 * The Kathmandu Post dates a story only to the day. Rendering that as a
 * relative time would tell a reader a story from this afternoon is "22
 * hours old" — a specific, confident, wrong number. Carrying the precision
 * lets the row say "Today" instead of inventing an hour.
 */
export type DatePrecision = "exact" | "day";
