// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Contact } from "./Contact";
import type { ReminderTemplate } from "./ReminderTemplate";
import type { RenewalGuide } from "./RenewalGuide";
import type { Website } from "./Website";

export type DirectoryPack = { contacts: Array<Contact>, websites: Array<Website>, reminderTemplates: Array<ReminderTemplate>, renewalGuides: { [key in string]?: RenewalGuide }, };
