// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DirectoryPack } from "./DirectoryPack";

/**
 * The directory pack, wrapped so its bindings are generated with the
 * rest of the contract.
 */
export type DirectoryResponse = { directory: DirectoryPack, };
