// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BookClosure } from "./BookClosure";
import type { Freshness } from "./Freshness";

export type DividendSnapshot = { 
/**
 * Soonest first.
 */
closures: Array<BookClosure>, freshness: Freshness, };
