// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-feed liveness, served at `/v1/health`.
 */
export type FeedHealth = { module: string, lastSuccess: string | null, consecutiveFailures: number, };
