// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One day's NRB rate for one currency, per its quoted `unit`.
 */
export type ForexPoint = { 
/**
 * UTC midnight of the date the rate applies to, in seconds.
 */
time: number, buy: number, sell: number, };
