// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ForexRate } from "./ForexRate";
import type { Freshness } from "./Freshness";

export type ForexSnapshot = { rates: Array<ForexRate>, 
/**
 * Buy rate per currency across the requested window, oldest first.
 *
 * The provider already asks NRB for a date range so a non-publishing
 * day falls back to rates still in force; keeping the rest of that
 * response is enough for a trend line at no extra request cost.
 */
history: { [key in string]?: Array<number> }, 
/**
 * The date the rates apply to.
 */
date: string, 
/**
 * NRB's own publish and revise timestamps — PRD §5.5 requires showing
 * the source's time, not only when Sajilo fetched it.
 */
publishedOn: string | null, modifiedOn: string | null, freshness: Freshness, };
