// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One currency's buy/sell rate as published by NRB.
 */
export type ForexRate = { currencyCode: string, currencyName: string, 
/**
 * How many units of the currency the quote covers. NRB quotes INR per
 * 100, JPY per 10 and KRW per 100; treating those as per-1 misprices
 * them by two orders of magnitude.
 */
unit: number, 
/**
 * NPR paid for `unit` of this currency.
 */
buy: number, 
/**
 * NPR charged for `unit` of this currency.
 */
sell: number, };
