// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ForexPoint } from "./ForexPoint";
import type { Freshness } from "./Freshness";

/**
 * A year of daily rates for every currency NRB publishes, oldest
 * first: what the forex chart draws from. One request a quarter of the
 * year, fetched once a day.
 */
export type ForexHistory = { 
/**
 * By ISO code.
 */
series: { [key in string]?: Array<ForexPoint> }, 
/**
 * How many units each currency's points are quoted per (INR: 100).
 */
units: { [key in string]?: number }, freshness: Freshness, };
