// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * When a payload was fetched and how old the source says it is. Carried
 * alongside every module so the UI can label a value without guessing.
 */
export type Freshness = { 
/**
 * When Sajilo fetched it.
 */
fetchedAt: string, 
/**
 * The timestamp the *source* published, when it gives one. Showing
 * only the fetch time would call a week-old bank rate "just now".
 */
sourceTimestamp: string | null, };
