// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A price that took effect on a day and stood until the next.
 */
export type FuelPoint = { 
/**
 * UTC midnight of the day it took effect, in seconds.
 */
time: number, price: number, };
