// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Fuel } from "./Fuel";

/**
 * Nepal Oil Corporation's retail price for one fuel.
 *
 * NOC revises prices on a schedule rather than continuously, so a price is
 * effective from a date and stands until the next revision. `change`
 * compares against the revision before it.
 */
export type FuelPrice = { fuel: Fuel, price: number, previousPrice: number, };
