// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Freshness } from "./Freshness";
import type { FuelPrice } from "./FuelPrice";

export type FuelPriceSnapshot = { prices: Array<FuelPrice>, 
/**
 * The date NOC's current rate took effect.
 */
effectiveFrom: string, freshness: Freshness, };
