// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FeedHealth } from "./FeedHealth";

export type Health = { feeds: Array<FeedHealth>, };
