// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One row from CDSC's server-rendered Current Issue Update table.
 */
export type IpoIssue = { 
/**
 * Stable across refreshes: the raw name cell with both dates. What the
 * app remembers an issue by, e.g. when the user marks it applied.
 */
id: string, 
/**
 * The cell exactly as CDSC publishes it, e.g.
 * `Beni Hydropower Project Limited - BENI (IPO - For General Public)`.
 */
companyName: string, 
/**
 * The company alone, without symbol or issue description. The whole
 * cell when it does not follow CDSC's usual shape.
 */
name: string, symbol: string | null, 
/**
 * `IPO`, `FPO`, `Right Share`, … as CDSC words it.
 */
issueType: string | null, 
/**
 * Who may apply, e.g. `General Public`, without CDSC's leading "For".
 */
audience: string | null, 
/**
 * Whether anyone can apply. False for right shares and reserved quotas
 * (foreign employment, project-affected locals): real issues, but not
 * ones to put in front of everybody.
 */
openToPublic: boolean, issueManager: string, 
/**
 * Kept as source text: CDSC publishes whole units, often with separators.
 */
issuedUnits: string, applicationCount: string, appliedUnits: string, amount: string, 
/**
 * ISO `YYYY-MM-DD`, as published by CDSC.
 */
openDate: string, 
/**
 * ISO `YYYY-MM-DD`, as published by CDSC.
 */
closeDate: string, lastUpdate: string, };
