// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Freshness } from "./Freshness";
import type { IpoIssue } from "./IpoIssue";

export type IpoSnapshot = { issues: Array<IpoIssue>, freshness: Freshness, };
