// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How much a caller should trust the value it is holding.
 */
export type LoadState<T> = { "status": "loading" } | { "status": "fresh", "value": T } | { "status": "stale", "value": T } | { "status": "unavailable" } | { "status": "failed", "value": string };
