// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * NEPSE itself or one of its sector sub-indices.
 */
export type MarketIndex = { name: string, value: number, change: number, changePercent: number, turnover: number, };
