// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How many traded companies closed up, down, or level on the day.
 */
export type MarketBreadth = { advanced: number, declined: number, unchanged: number, };
