// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Kalimati quotes almost everything per kilogram, bananas by the dozen,
 * and pineapple by the piece.
 */
export type MarketUnit = "kilogram" | "dozen" | "piece";
