// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MoverBoard } from "./MoverBoard";

/**
 * A row from one of the market page's four leaderboards.
 */
export type MarketMover = { board: MoverBoard, symbol: string, ltp: number, 
/**
 * Percent for gainers/losers; rupees or shares for the other two.
 */
metric: number, };
