// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * NEPSE's own open/closed flag, read separately from the price snapshot
 * so the UI never has to infer it from prices or the calendar.
 */
export type MarketStatus = { isOpen: boolean, };
