// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A lightweight exchange state from YONEPSE, kept separate from the
 * ShareSansar price snapshot so the UI never has to infer it from prices.
 */
export type MarketStatus = { isOpen: boolean, };
