// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The Federation quotes per tola and per 10 grams, never per gram.
 */
export type MetalUnit = "tola" | "tenGram";
