// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Metal } from "./Metal";
import type { MetalUnit } from "./MetalUnit";

/**
 * Gold and silver as the Federation publishes them.
 *
 * Rates are quoted per unit, in spite of the field name the upstream API
 * uses: its `todayBaseRatePerGram` holds 305,200 for one tola of gold, so
 * reading it as a per-gram figure would be out by orders of magnitude.
 */
export type MetalRate = { metal: Metal, unit: MetalUnit, price: number, previousPrice: number, };
