// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One trading day's price per tola.
 */
export type MetalPoint = { 
/**
 * UTC midnight of the trading day, in seconds.
 */
time: number, price: number, };
