// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Freshness } from "./Freshness";
import type { MetalPoint } from "./MetalPoint";

/**
 * A year of hallmark gold and silver per tola, oldest first, for the
 * chart. Trading days only: the market closes on Saturdays and
 * holidays, and those dates are absent rather than zero.
 */
export type MetalHistory = { gold: Array<MetalPoint>, silver: Array<MetalPoint>, freshness: Freshness, };
