// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Freshness } from "./Freshness";
import type { MetalRate } from "./MetalRate";

export type MetalRateSnapshot = { rates: Array<MetalRate>, 
/**
 * Gold price per tola over the last week, oldest first.
 */
goldHistory: Array<number>, freshness: Freshness, };
