// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Freshness } from "./Freshness";
import type { MetalRate } from "./MetalRate";
import type { MetalSource } from "./MetalSource";

export type MetalRateSnapshot = { 
/**
 * Who published these prices. The Federation, unless it was down
 * and a fallback answered; the screen credits whichever did.
 */
source: MetalSource, rates: Array<MetalRate>, 
/**
 * Gold price per tola over the last week, oldest first.
 */
goldHistory: Array<number>, freshness: Freshness, };
