// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where gold and silver prices came from, for the credit under them.
 */
export type MetalSource = "fenegosida" | "nepaliPatro" | "hamroPatro";
