// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Meta = { 
/**
 * Clients older than this are asked to update. Lets a breaking change
 * to the contract be rolled out without bricking older installs
 * silently.
 */
minClientVersion: string, 
/**
 * A short notice shown in Settings — maintenance windows, a source
 * that has gone away for good.
 */
notice: string | null, };
