// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The monthly NAV. Fund managers publish it against a Bikram Sambat
 * month rather than a day, so it carries that month instead of a date.
 */
export type MonthlyNav = { nav: number, bsYear: number, 
/**
 * 1 = Baishakh … 12 = Chaitra.
 */
bsMonth: number, 
/**
 * e.g. `Shrawan`.
 */
monthName: string, 
/**
 * e.g. `साउन`.
 */
monthNameNe: string, };
