// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One of the four leaderboards on ShareSansar's market page.
 */
export type MoverBoard = "gainers" | "losers" | "turnover" | "volume";
