// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FundKind } from "./FundKind";
import type { MonthlyNav } from "./MonthlyNav";
import type { NavPoint } from "./NavPoint";

export type MutualFund = { symbol: string, name: string, kind: FundKind, 
/**
 * The fund manager's logo, as a full https URL. Only ShareHub sends
 * one, and not for every scheme.
 */
logoUrl: string | null, 
/**
 * The newest NAV the manager has published: the daily one where the
 * scheme publishes daily, otherwise the weekly one.
 */
latest: NavPoint, 
/**
 * The weekly NAV `latest` moved from, when it is an older figure.
 * `None` when the weekly NAV is itself the latest.
 */
previous: NavPoint | null, daily: NavPoint | null, weekly: NavPoint | null, monthly: MonthlyNav | null, 
/**
 * Rupees under management.
 */
fundSize: number | null, 
/**
 * Closed-end only: the last traded price on NEPSE.
 */
ltp: number | null, 
/**
 * ISO `YYYY-MM-DD`: the day `ltp` traded. A thinly traded fund's last
 * price can be days old, and the discount is only as current as it.
 */
ltpDate: string | null, 
/**
 * Closed-end only: how far the market price sits from the weekly NAV,
 * in percent. Negative is a discount.
 */
premiumPercent: number | null, 
/**
 * ISO `YYYY-MM-DD`. Closed-end and matured schemes only; open-end
 * ones never mature.
 */
maturityDate: string | null, 
/**
 * Matured only: what each unit is paid out at on winding up.
 */
refundNav: number | null, 
/**
 * How many companies the scheme holds shares in.
 */
holdings: number | null, 
/**
 * How many shares it holds across those companies, in total.
 */
heldShares: number | null, };
