// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Freshness } from "./Freshness";
import type { MutualFund } from "./MutualFund";

export type MutualFundSnapshot = { 
/**
 * Open-end first, then closed-end, then matured; by name within each.
 */
funds: Array<MutualFund>, 
/**
 * Which site answered, for the source note.
 */
source: string, freshness: Freshness, };
