// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Freshness } from "./Freshness";
import type { NavHistoryPoint } from "./NavHistoryPoint";

/**
 * An open-end fund's NAV over the years it has published, oldest first:
 * daily where the manager publishes daily, weekly before that.
 */
export type NavHistory = { symbol: string, points: Array<NavHistoryPoint>, source: string, freshness: Freshness, };
