// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One NAV on a fund's chart.
 */
export type NavHistoryPoint = { 
/**
 * Seconds since 1970: midnight UTC of the day the NAV is as of, the
 * way a share's daily chart marks its days.
 */
time: number, nav: number, };
