// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One published NAV and the Nepal calendar day it is as of.
 */
export type NavPoint = { nav: number, 
/**
 * ISO `YYYY-MM-DD`.
 */
date: string, };
