// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A Bikram Sambat calendar date. Ordering is lexicographic on
 * (year, month, day), matching `NepaliDate: Comparable` in Swift.
 */
export type NepaliDate = { year: number, month: number, day: number, };
