// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DatePrecision } from "./DatePrecision";
import type { NewsAttachment } from "./NewsAttachment";
import type { NewsSource } from "./NewsSource";

/**
 * A single headline.
 *
 * Publisher entries deliberately retain only a title, a link, and where
 * they came from. Official government notices additionally retain their
 * public body and attachments so Sajilo can provide a usable detail view.
 */
export type NewsItem = { id: string | null, title: string, link: string, source: NewsSource, sourceName: string, published: string | null, precision: DatePrecision, content: string | null, department: string | null, tags: Array<string>, attachments: Array<NewsAttachment>, };
