// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NewsSource } from "./NewsSource";

/**
 * One entry in the source picker.
 *
 * Sent rather than duplicated in TypeScript so the publisher names and the
 * language split have exactly one definition — this file.
 */
export type NewsSourceInfo = { id: NewsSource, name: string, english: boolean, };
