// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The feeds Sajilo reads.
 *
 * Every one is an official publisher RSS endpoint returning
 * `application/rss+xml`. Kantipur and Hamro Patro are deliberately absent:
 * neither publishes a real feed, and parsing their HTML is the same
 * technique that silently cost this app 349 days of bundled festival data.
 */
export type NewsSource = "onlineKhabar" | "onlineKhabarEnglish" | "annapurnaPost" | "ratopati" | "bizkhabar" | "kathmanduPost" | "khabarhub" | "risingNepal" | "ratopatiEnglish";
