// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PackNewsSource } from "./PackNewsSource";

/**
 * Newsrooms added without a release: `data/config/news-sources.json`.
 */
export type NewsSourcesPack = { sources: Array<PackNewsSource>, };
