// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Freshness } from "./Freshness";
import type { NewsItem } from "./NewsItem";

export type NewsDigest = { items: Array<NewsItem>, 
/**
 * Sources that failed this round, so partial results can say so rather
 * than quietly presenting themselves as the whole picture.
 */
failedSources: Array<string>, freshness: Freshness, };
