// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A file attached to an official government update.
 */
export type NewsAttachment = { id: string, filename: string, mimeType: string, size: number, url: string, };
