// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One entry in the source picker.
 *
 * Sent rather than duplicated in TypeScript so the publisher names and the
 * language split have exactly one definition — this file.
 */
export type NewsSourceInfo = { 
/**
 * A built-in source's `NewsSource` name, or a pack source's id —
 * what a headline's `source_key ?? source` is compared with.
 */
id: string, name: string, english: boolean, official: boolean, };
