// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DatePrecision } from "./DatePrecision";
import type { NewsSource } from "./NewsSource";

/**
 * A single headline.
 *
 * Deliberately just a title, a link, and where it came from. The feeds
 * carry more — OnlineKhabar ships `content:encoded` with the whole article
 * body — and none of it is read. Syndicating a feed is not a licence to
 * republish what it contains.
 */
export type NewsItem = { title: string, link: string, source: NewsSource, sourceName: string, 
/**
 * Absent in some feeds — Annapurna Post publishes no `pubDate` at all
 * — so nothing may depend on it being there.
 */
published: string | null, precision: DatePrecision, };
