// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The feeds Sajilo reads.
 *
 * Most are publisher RSS endpoints returning `application/rss+xml`.
 * Kantipur and Nepal Government are the exceptions: both expose the
 * keyless JSON endpoints their own front ends use, so Sajilo reads those
 * rather than scraping rendered HTML.
 *
 * Three papers are deliberately absent. Hamro Patro offers nothing but
 * HTML, and parsing that is the technique that silently cost this app 349
 * days of bundled festival data. The Himalayan Times published perfectly
 * good per-section feeds until it put the whole site behind a Sucuri
 * JavaScript challenge: every request now answers `307` into a page that
 * says scripting is required. A browser solves it, an HTTP client cannot,
 * and defeating a bot check to read a newspaper is not something this app
 * does. It was removed rather than left to fail on every refresh — an
 * error line that is always there is one nobody reads when it matters.
 *
 * The Rising Nepal went the same way in August 2026, for a duller reason:
 * its host answers ICMP but refuses every TCP connection on 80 and 443,
 * from inside Nepal and abroad alike, while `gorkhapatraonline.com` — the
 * same publisher, the neighbouring address in the same /24 — serves fine.
 * Nothing was announced and Gorkhapatra still links to
 * `risingnepaldaily.com`, so there is no new feed to follow. Note that
 * `risingnep.com` is not one: that domain lapsed and now serves gambling
 * spam under the paper's old title. Gorkhapatra, its Nepali sibling from
 * the same publisher, is read in its place and answers fine.
 */
export type NewsSource = "nepalGovernment" | "onlineKhabar" | "onlineKhabarEnglish" | "annapurnaPost" | "ratopati" | "bizkhabar" | "kathmanduPost" | "khabarhub" | "ratopatiEnglish" | "kantipur" | "gorkhapatra";
