// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NoteTextPart } from "./NoteTextPart";

/**
 * A search result, with the words that matched marked.
 */
export type NoteSearchHit = { id: string, folderId: string, title: Array<NoteTextPart>, snippet: Array<NoteTextPart>, };
