// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A note in the Trash, most recently deleted first.
 */
export type NoteTrashed = { id: string, title: string, preview: string, deletedAt: string, 
/**
 * Days until it's deleted for good.
 */
daysLeft: number, };
