// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A note as the list shows it.
 */
export type NoteSummary = { id: string, folderId: string, 
/**
 * The first line, plain. Empty for a note with nothing in it yet.
 */
title: string, preview: string, tags: Array<string>, openTasks: number, doneTasks: number, pinned: boolean, createdAt: string, updatedAt: string, 
/**
 * Which heading the list files it under (`today`, `yesterday`,
 * `week`, or `2083-05` for a BS month), and that heading's words.
 */
group: string, groupLabel: string, };
