// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NoteFolder } from "./NoteFolder";
import type { NoteSummary } from "./NoteSummary";

/**
 * Everything the Notes tab's list needs, newest first, pinned on top.
 */
export type NotesList = { folders: Array<NoteFolder>, notes: Array<NoteSummary>, 
/**
 * The note open when Notes was last left, to open it again.
 */
lastOpen: string | null, 
/**
 * How many notes are in the Trash.
 */
trashCount: number, };
