// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a save changed.
 */
export type NoteSaved = { id: string, revision: number, title: string, };
