// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A folder, with how many notes (not in the Trash) it holds.
 */
export type NoteFolder = { id: string, name: string, 
/**
 * `daily` for the folder the day's notes go in, `user` otherwise.
 */
role: string, count: number, };
