// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NoteBacklink } from "./NoteBacklink";

/**
 * One note, to edit.
 */
export type NoteDocument = { id: string, folderId: string, 
/**
 * The note itself, in Markdown.
 */
body: string, 
/**
 * Goes up with every save; a save must name the revision it edited.
 */
revision: number, 
/**
 * Where the cursor was, in characters from the start.
 */
cursor: number | null, 
/**
 * Notes that link here with `[[this note]]`.
 */
linkedFrom: Array<NoteBacklink>, };
