// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NoteBacklink = { id: string, title: string, 
/**
 * The line that holds the link, plain.
 */
line: string, };
