// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PackSource } from "./PackSource";

export type PackStatus = { name: string, source: PackSource, };
