// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A newsroom added by config: any site with an RSS or Atom feed.
 */
export type PackNewsSource = { 
/**
 * Stable once published: a reader's chosen filter is saved by it.
 */
id: string, name: string, feeds: Array<string>, english: boolean, };
