// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Place = { 
/**
 * Stable, lowercase, e.g. `dhangadhi`. Kept once published: it is what a
 * pin and a cache entry are stored under.
 */
id: string, name: string, nameNe: string, district: string, districtNe: string, province: string, provinceNe: string, latitude: number, longitude: number, 
/**
 * Metres, from the same terrain model the forecast is downscaled with.
 */
elevation: number, };
