// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RadioStation } from "./RadioStation";

/**
 * Corrections to the live directory: `data/config/radio.json`.
 *
 * The directory is scraped from Ratopati and changes without notice.
 * This adds stations it lacks, hides dead ones, and replaces a stream
 * that moved, without a release.
 */
export type RadioPack = { 
/**
 * Shown alongside the directory's; one with a directory slug
 * replaces that entry.
 */
add: Array<RadioStation>, 
/**
 * Slugs never shown.
 */
hide: Array<string>, 
/**
 * Slug → stream URL, used instead of the station page's.
 */
streams: { [key in string]?: string }, };
