// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One station in Ratopati's Nepal radio directory.
 */
export type RadioStation = { slug: string, name: string, frequency: string | null, logoUrl: string | null, 
/**
 * The direct stream URL the webview plays. Absent when the directory
 * lists a station it has no playable source for.
 */
streamUrl: string | null, };
