// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Freshness } from "./Freshness";
import type { RadioStation } from "./RadioStation";

export type RadioDirectory = { stations: Array<RadioStation>, freshness: Freshness, };
