// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Who published the readings on screen.
 */
export type RashifalSource = "hamroPatro" | "ratopati";
