// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Freshness } from "./Freshness";
import type { Rashifal } from "./Rashifal";
import type { RashifalPeriod } from "./RashifalPeriod";
import type { RashifalSource } from "./RashifalSource";

export type RashifalSnapshot = { readings: Array<Rashifal>, period: RashifalPeriod, 
/**
 * The span as the source names it: "साप्ताहिक राशिफल असोज २०८३, साता ३".
 */
title: string | null, source: RashifalSource, freshness: Freshness, };
