// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The twelve rashi, in their canonical order.
 *
 * These are the same twelve divisions as the Bikram Sambat solar months,
 * because a BS month is the span the sun spends in one rashi. That
 * correspondence is deliberately *not* used to pick a reader's sign for
 * them: in Nepali practice your rashi is normally the **moon** sign from
 * your birth chart, or the one a jyotish assigned from the first syllable
 * of your name. Deriving it from a birth date would give the sun sign and
 * quietly hand most people the wrong reading, so the sign is always
 * chosen by hand.
 */
export type RashiSign = "mesh" | "vrish" | "mithun" | "karkat" | "simha" | "kanya" | "tula" | "vrishchik" | "dhanu" | "makar" | "kumbha" | "meen";
