// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Freshness } from "./Freshness";
import type { Rashifal } from "./Rashifal";

export type RashifalSnapshot = { readings: Array<Rashifal>, freshness: Freshness, };
