// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RashiSign } from "./RashiSign";

/**
 * One sign's reading for the day.
 */
export type Rashifal = { sign: RashiSign, 
/**
 * The astrologer's words, carried verbatim. Never trimmed,
 * summarised, or reflowed — it is someone's writing, and Sajilo shows
 * it as published.
 */
prediction: string, 
/**
 * The day's lucky colour, when the reading names one ("आजको शुभ
 * रंग सेतो…"). Lifted out of the text, which keeps saying it too.
 */
luckyColour: string | null, 
/**
 * The day's lucky number, as written (Devanagari digits).
 */
luckyNumber: string | null, };
