// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RashiSign } from "./RashiSign";

/**
 * One sign's reading for the day.
 */
export type Rashifal = { sign: RashiSign, 
/**
 * The astrologer's words, carried verbatim. Never trimmed,
 * summarised, or reflowed — it is someone's writing, and Sajilo shows
 * it as published.
 */
prediction: string, };
