// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TemplateCategory } from "./TemplateCategory";
import type { TemplateRecurrence } from "./TemplateRecurrence";

export type ReminderTemplate = { id: string, title: string, category: TemplateCategory, 
/**
 * What to have ready, where to pay, what lateness costs.
 */
tips: Array<string>, 
/**
 * Empty when there is no one official site (an internet bill).
 */
url: string, recurrence?: TemplateRecurrence, remindDays: Array<number>, };
