// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PackStatus } from "./PackStatus";

export type RemoteConfigStatus = { 
/**
 * The rev of the last manifest applied; `None` before the first.
 * A Unix timestamp, well inside a JS number.
 */
rev: number | null, 
/**
 * The last time the manifest was checked, successfully or not.
 */
checkedAt: string | null, 
/**
 * Why the last check did not apply everything, if it didn't.
 */
error: string | null, packs: Array<PackStatus>, };
