// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RenewalGuide = { url: string, fee: string, location: string, checklist: Array<string>, note?: string, };
