// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A figure reported for a fiscal year (and quarter), as NEPSE sites give
 * them: `10.81` for `FY:082-083, Q:4`.
 */
export type ReportedFigure = { value: number, 
/**
 * The period as the source writes it, e.g. `FY 082/83 · Q4`; empty
 * when none is given.
 */
period: string, };
