// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NepaliDate } from "./NepaliDate";

/**
 * Where one fund's schedule stands today.
 */
export type SipStatus = { symbol: string, name: string, day: number, amount: number | null, 
/**
 * ISO date of the payment this status is about: the next one, or one
 * missed within the last `GRACE_DAYS` days.
 */
due: string, 
/**
 * The same day in Bikram Sambat, when it is inside the bundled calendar.
 */
dueBs: NepaliDate | null, 
/**
 * e.g. `Ashwin`.
 */
dueBsMonth: string | null, 
/**
 * e.g. `असोज`.
 */
dueBsMonthNe: string | null, 
/**
 * Days from today to `due`. Negative once it has been missed.
 */
days: number, };
