// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Freshness } from "./Freshness";
import type { MarketBreadth } from "./MarketBreadth";
import type { MarketIndex } from "./MarketIndex";
import type { MarketMover } from "./MarketMover";
import type { MarketStatus } from "./MarketStatus";
import type { StockQuote } from "./StockQuote";

export type StockMarketSnapshot = { nepse: MarketIndex | null, marketStatus: MarketStatus | null, 
/**
 * Counted from the price table, so it always agrees with the quotes.
 */
breadth: MarketBreadth | null, subIndices: Array<MarketIndex>, movers: Array<MarketMover>, quotes: Array<StockQuote>, freshness: Freshness, };
