// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Freshness } from "./Freshness";
import type { ReportedFigure } from "./ReportedFigure";

/**
 * What a company is worth and pays, from Merolagani's company page.
 * Every figure may be missing: a newly listed company has no EPS yet, a
 * mutual fund no book value.
 */
export type StockFundamentals = { symbol: string, sector: string | null, sharesOutstanding: number | null, marketCap: number | null, eps: ReportedFigure | null, peRatio: number | null, bookValue: number | null, pbv: number | null, 
/**
 * Cash dividend and bonus share, percent of paid-up value.
 */
cashDividend: ReportedFigure | null, bonusShare: ReportedFigure | null, rightShare: string | null, 
/**
 * Price change over the last year, percent.
 */
oneYearYield: number | null, averageVolume30Day: number | null, paidUpValue: number | null, source: string, freshness: Freshness, };
