// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StockTradeCharges } from "./StockTradeCharges";

export type StockTradeEstimate = { gross: number, charges: StockTradeCharges, tax: number, 
/**
 * Purchase: amount paid. Sale: amount receivable after fees and tax.
 */
net: number, realisedProfitLoss: number | null, remainingQuantity: number | null, };
