// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One row from ShareSansar's public price table.
 */
export type StockQuote = { symbol: string, companyName: string | null, ltp: number, previousClose: number, change: number, changePercent: number, open: number | null, high: number | null, low: number | null, close: number | null, vwap: number | null, volume: number | null, turnover: number, transactions: number | null, week52High: number | null, week52Low: number | null, average120Day: number | null, average180Day: number | null, };
