// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Freshness } from "./Freshness";
import type { StockChartPoint } from "./StockChartPoint";

/**
 * A share's price over a range, oldest first.
 */
export type StockChart = { symbol: string, 
/**
 * `1d` (the latest session, trade by trade), `1w`, `1m`, `3m`, `1y`
 * or `5y` (one close per trading day).
 */
range: string, points: Array<StockChartPoint>, source: string, freshness: Freshness, };
