// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One point on a share's chart: a moment and the price then.
 */
export type StockChartPoint = { 
/**
 * Seconds since 1970, UTC. A trade's own moment for a session's
 * chart; midnight UTC of the trading day for longer ranges.
 */
time: number, price: number, volume: number, };
