// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StockAcquisitionSource } from "./StockAcquisitionSource";
import type { StockTransactionKind } from "./StockTransactionKind";

/**
 * One user-owned record. Rupee values cross the wire as decimals; the desktop
 * database stores them as integer paisa.
 */
export type StockTransaction = { id: string, symbol: string, kind: StockTransactionKind, 
/**
 * Gregorian ISO date. The UI also presents its Bikram Sambat equivalent.
 */
tradeDate: string, quantity: number, price: number, fees: number, tax: number, feesEstimated: boolean, taxEstimated: boolean, source: StockAcquisitionSource | null, note: string, };
