// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Stored on reminders for filtering and backups.
 */
export type TemplateCategory = "identity" | "vehicle" | "home" | "money" | "health" | "application";
