// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MarketUnit } from "./MarketUnit";

/**
 * One day's **wholesale** rate for one item at the Kalimati market — not
 * what a neighbourhood shop charges. The UI says so explicitly.
 */
export type VegetablePrice = { 
/**
 * The Nepali name exactly as the board publishes it, qualifiers
 * included: "गोलभेडा ठूलो(नेपाली)". Never cleaned up — the qualifier
 * separates a local tomato from an Indian one, and they differ in
 * price.
 */
name: string, unit: MarketUnit, minimum: number, maximum: number, average: number, 
/**
 * An English name for the items where one is unambiguous. Absent
 * rather than guessed for the rest: a wrong label on a price list is
 * worse than no label — someone buys the wrong thing.
 */
englishName: string | null, };
