// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Freshness } from "./Freshness";
import type { NepaliDate } from "./NepaliDate";
import type { VegetablePrice } from "./VegetablePrice";

export type VegetableMarketSnapshot = { prices: Array<VegetablePrice>, 
/**
 * The board dates its own table in Bikram Sambat — "वि.सं. साउन ३१,
 * २०८३" — which is the calendar this app already speaks.
 */
publishedOn: NepaliDate | null, freshness: Freshness, };
