// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WeatherCondition = "clear" | "partlyCloudy" | "overcast" | "fog" | "drizzle" | "rain" | "snow" | "showers" | "thunderstorm" | "unknown";
