// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AirQuality } from "./AirQuality";
import type { DailyForecast } from "./DailyForecast";
import type { Freshness } from "./Freshness";
import type { WeatherCondition } from "./WeatherCondition";
import type { WeatherLocation } from "./WeatherLocation";

export type WeatherSnapshot = { 
/**
 * Which place this reading describes. Without it a cached Kathmandu
 * reading could be rendered under a Pokhara heading.
 */
location: WeatherLocation, temperatureCelsius: number, apparentTemperatureCelsius: number, precipitationChance: number, highCelsius: number, lowCelsius: number, condition: WeatherCondition, 
/**
 * Today's sunrise and sunset at the selected location, used to place
 * the sky phase against the real day rather than fixed clock hours.
 */
sunrise: string | null, sunset: string | null, 
/**
 * Today first, then the following days (PRD §5.4).
 */
daily: Array<DailyForecast>, 
/**
 * Optional by design: air quality comes from a separate endpoint, and
 * a forecast is still worth showing when only that one is unreachable.
 */
airQuality: AirQuality | null, 
/**
 * When the reading was taken at source. `freshness` records when
 * Sajilo retrieved it; this is what the user is told.
 */
observedAt: string, freshness: Freshness, };
