// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WebsiteType } from "./WebsiteType";

export type Website = { name: string, nameNe: string, description: string, descriptionNe: string, type: WebsiteType, url: string, };
