#!/bin/zsh
set -euo pipefail

# Regenerates appcast.xml from the GitHub releases that actually exist.
#
# This has to run on the maintainer's Mac, not in CI: each entry is signed with
# the private EdDSA key held in the login Keychain, and that key is what proves
# an update came from you. Sajilo is only ad-hoc signed, so Gatekeeper cannot
# vouch for a download — the EdDSA signature is the *only* thing standing
# between a user and a substituted update. It never leaves this machine.
#
#   ./scripts/update-appcast.sh
#
# The whole file is rewritten from the published releases every run rather than
# having a new item spliced into it, so running it twice cannot produce
# duplicate or stale entries, and a release deleted upstream disappears here.

PROJECT_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
WORK_DIR="$PROJECT_ROOT/.build/appcast"
APPCAST_PATH="$PROJECT_ROOT/appcast.xml"
SIGN_UPDATE="$PROJECT_ROOT/.build/artifacts/sparkle/Sparkle/bin/sign_update"
REPO="adarshaacharya/sajilo"
ARCHIVE_NAME="Sajilo-macos-arm64.zip"
MINIMUM_SYSTEM_VERSION="14.0"

cd "$PROJECT_ROOT"

if [[ ! -x "$SIGN_UPDATE" ]]; then
  # The tool ships inside Sparkle's binary artifact, which only exists after a
  # resolve. Building is cheaper to do than to explain.
  echo "Fetching Sparkle's signing tool…"
  swift build --product Sajilo >/dev/null
fi
[[ -x "$SIGN_UPDATE" ]] || { echo "sign_update not found at $SIGN_UPDATE"; exit 1; }

mkdir -p "$WORK_DIR"

# Oldest first, so the feed reads as a history and the newest item lands last.
TAGS=($(gh release list --repo "$REPO" --limit 50 --json tagName --jq '.[].tagName' | tail -r))
[[ ${#TAGS[@]} -gt 0 ]] || { echo "No releases published for $REPO"; exit 1; }

ITEMS=""

for TAG in "${TAGS[@]}"; do
  ARCHIVE="$WORK_DIR/$TAG-$ARCHIVE_NAME"
  UNPACKED="$WORK_DIR/$TAG"

  if [[ ! -f "$ARCHIVE" ]]; then
    echo "Downloading $TAG…"
    gh release download "$TAG" --repo "$REPO" --pattern "$ARCHIVE_NAME" --output "$ARCHIVE" --clobber
  fi

  # Versions are read out of the archive itself, never from the working tree.
  # The tree has usually moved on to the next version by the time this runs, and
  # an appcast that advertises a version the download does not contain sends
  # every user into an update loop.
  rm -rf "$UNPACKED"
  mkdir -p "$UNPACKED"
  ditto -x -k "$ARCHIVE" "$UNPACKED"
  INFO_PLIST="$UNPACKED/Sajilo.app/Contents/Info.plist"
  [[ -f "$INFO_PLIST" ]] || { echo "$TAG: no Sajilo.app inside $ARCHIVE_NAME"; exit 1; }

  BUILD=$(/usr/libexec/PlistBuddy -c 'Print :CFBundleVersion' "$INFO_PLIST")
  SHORT_VERSION=$(/usr/libexec/PlistBuddy -c 'Print :CFBundleShortVersionString' "$INFO_PLIST")

  # `sign_update` prints the two enclosure attributes ready to paste.
  SIGNATURE_ATTRIBUTES=$("$SIGN_UPDATE" "$ARCHIVE")

  PUBLISHED_AT=$(gh release view "$TAG" --repo "$REPO" --json publishedAt --jq '.publishedAt')
  PUB_DATE=$(TZ=UTC date -j -f "%Y-%m-%dT%H:%M:%SZ" "$PUBLISHED_AT" "+%a, %d %b %Y %H:%M:%S +0000")

  # "v0.1.0-beta.2" reads as "0.1.0 beta 2".
  TITLE="Sajilo ${${TAG#v}//-beta./ beta }"
  RELEASE_URL="https://github.com/$REPO/releases/tag/$TAG"

  echo "  $TAG → $TITLE (build $BUILD)"

  ITEMS+="        <item>
            <title>$TITLE</title>
            <link>$RELEASE_URL</link>
            <sparkle:version>$BUILD</sparkle:version>
            <sparkle:shortVersionString>$SHORT_VERSION</sparkle:shortVersionString>
            <sparkle:minimumSystemVersion>$MINIMUM_SYSTEM_VERSION</sparkle:minimumSystemVersion>
            <pubDate>$PUB_DATE</pubDate>
            <description><![CDATA[<p>Release notes: <a href=\"$RELEASE_URL\">$TITLE</a></p>]]></description>
            <enclosure url=\"https://github.com/$REPO/releases/download/$TAG/$ARCHIVE_NAME\"
                       sparkle:os=\"macos\"
                       type=\"application/octet-stream\"
                       $SIGNATURE_ATTRIBUTES />
        </item>
"
done

cat > "$APPCAST_PATH" <<XML
<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by scripts/update-appcast.sh. Do not edit by hand: every
     enclosure carries an EdDSA signature over that exact archive, so editing a
     URL or a length here silently breaks the update it describes. -->
<rss version="2.0" xmlns:sparkle="http://www.andymatuschak.org/xml-namespaces/sparkle">
    <channel>
        <title>Sajilo Updates</title>
        <link>https://github.com/$REPO/releases</link>
        <description>Signed release updates for Sajilo.</description>
        <language>en</language>
$ITEMS    </channel>
</rss>
XML

echo
echo "Wrote $APPCAST_PATH with ${#TAGS[@]} release(s)."
echo "Commit and push it — Sparkle reads it from the main branch."
