import Foundation

enum AppLanguage: String, CaseIterable, Identifiable, Codable, Sendable {
    case mixed
    case english
    case nepali

    var id: String { rawValue }

    /// Mixed deliberately retains English utility labels while calendar data,
    /// tithi, festivals, and BS numerals remain in their original Nepali.
    var locale: Locale {
        switch self {
        case .nepali: Locale(identifier: "ne_NP")
        case .english, .mixed: Locale(identifier: "en")
        }
    }

    var title: LocalizedStringResource {
        switch self {
        case .mixed: L10n.languageMixed
        case .english: L10n.languageEnglish
        case .nepali: L10n.languageNepali
        }
    }

}

enum L10n {
    static let language = LocalizedStringResource("settings.language", bundle: .sajiloResources)
    static let languageMixed = LocalizedStringResource("language.mixed", bundle: .sajiloResources)
    static let languageEnglish = LocalizedStringResource("language.english", bundle: .sajiloResources)
    static let languageNepali = LocalizedStringResource("language.nepali", bundle: .sajiloResources)
    static let settings = LocalizedStringResource("screen.settings", bundle: .sajiloResources)
    static let back = LocalizedStringResource("action.back", bundle: .sajiloResources)
    static let festivals = LocalizedStringResource("action.festivals", bundle: .sajiloResources)
    static let convert = LocalizedStringResource("action.convert", bundle: .sajiloResources)
    static let quit = LocalizedStringResource("action.quit", bundle: .sajiloResources)
    static let weather = LocalizedStringResource("feature.weather", bundle: .sajiloResources)
    static let forex = LocalizedStringResource("feature.forex", bundle: .sajiloResources)
    static let display = LocalizedStringResource("settings.display", bundle: .sajiloResources)
    static let numerals = LocalizedStringResource("settings.numerals", bundle: .sajiloResources)
    static let news = LocalizedStringResource("screen.news", bundle: .sajiloResources)
    static let bazar = LocalizedStringResource("screen.bazar", bundle: .sajiloResources)
    static let rashifal = LocalizedStringResource("screen.rashifal", bundle: .sajiloResources)
    static let rashifalPickSign = LocalizedStringResource("rashifal.pick-sign", bundle: .sajiloResources)
    static let rashifalPickHint = LocalizedStringResource("rashifal.pick-hint", bundle: .sajiloResources)
    static let rashifalChangeSign = LocalizedStringResource("rashifal.change-sign", bundle: .sajiloResources)
    static let rashifalOtherSigns = LocalizedStringResource("rashifal.other-signs", bundle: .sajiloResources)
    static let rashifalCredit = LocalizedStringResource("rashifal.credit", bundle: .sajiloResources)
    static let rashifalStale = LocalizedStringResource("rashifal.stale", bundle: .sajiloResources)
    static let settingsRashifal = LocalizedStringResource("settings.rashifal", bundle: .sajiloResources)
    static let bazarMetals = LocalizedStringResource("bazar.metals", bundle: .sajiloResources)
    static let bazarFuel = LocalizedStringResource("bazar.fuel", bundle: .sajiloResources)
    static let bazarVegetables = LocalizedStringResource("bazar.vegetables", bundle: .sajiloResources)
    static let bazarSearchProduce = LocalizedStringResource("bazar.search-produce", bundle: .sajiloResources)
    static let bazarWholesaleNote = LocalizedStringResource("bazar.wholesale-note", bundle: .sajiloResources)
    static let bazarPinned = LocalizedStringResource("bazar.pinned", bundle: .sajiloResources)
    static let bazarAllProduce = LocalizedStringResource("bazar.all-produce", bundle: .sajiloResources)
    static let bazarNoMatch = LocalizedStringResource("bazar.no-match", bundle: .sajiloResources)
    static let bazarPin = LocalizedStringResource("bazar.pin", bundle: .sajiloResources)
    static let bazarQuantity = LocalizedStringResource("bazar.quantity", bundle: .sajiloResources)
    static let bazarWorth = LocalizedStringResource("bazar.worth", bundle: .sajiloResources)
    static let bazarPerGram = LocalizedStringResource("bazar.per-gram", bundle: .sajiloResources)
    static let bazarPublished = LocalizedStringResource("bazar.published", bundle: .sajiloResources)
    static let bazarEffectiveFrom = LocalizedStringResource("bazar.effective-from", bundle: .sajiloResources)
    static let settingsBazar = LocalizedStringResource("settings.bazar", bundle: .sajiloResources)
    static let bazarSource = LocalizedStringResource("settings.bazar-source", bundle: .sajiloResources)
    static let tools = LocalizedStringResource("tools.title", bundle: .sajiloResources)
    static let toolLand = LocalizedStringResource("tools.land", bundle: .sajiloResources)
    static let toolWeight = LocalizedStringResource("tools.weight", bundle: .sajiloResources)
    static let toolVAT = LocalizedStringResource("tools.vat", bundle: .sajiloResources)
    static let toolInterest = LocalizedStringResource("tools.interest", bundle: .sajiloResources)
    static let amount = LocalizedStringResource("tools.amount", bundle: .sajiloResources)
    static let unit = LocalizedStringResource("tools.unit", bundle: .sajiloResources)
    static let hillSystem = LocalizedStringResource("tools.hill-system", bundle: .sajiloResources)
    static let teraiSystem = LocalizedStringResource("tools.terai-system", bundle: .sajiloResources)
    static let area = LocalizedStringResource("tools.area", bundle: .sajiloResources)
    static let priceIncludesVAT = LocalizedStringResource("tools.price-includes-vat", bundle: .sajiloResources)
    static let baseAmount = LocalizedStringResource("tools.base-amount", bundle: .sajiloResources)
    static let vatAmount = LocalizedStringResource("tools.vat-amount", bundle: .sajiloResources)
    static let total = LocalizedStringResource("tools.total", bundle: .sajiloResources)
    static let principal = LocalizedStringResource("tools.principal", bundle: .sajiloResources)
    static let ratePercent = LocalizedStringResource("tools.rate-percent", bundle: .sajiloResources)
    static let years = LocalizedStringResource("tools.years", bundle: .sajiloResources)
    static let interest = LocalizedStringResource("tools.interest-amount", bundle: .sajiloResources)
    static let aqiGood = LocalizedStringResource("aqi.good", bundle: .sajiloResources)
    static let aqiModerate = LocalizedStringResource("aqi.moderate", bundle: .sajiloResources)
    static let aqiSensitive = LocalizedStringResource("aqi.sensitive", bundle: .sajiloResources)
    static let aqiUnhealthy = LocalizedStringResource("aqi.unhealthy", bundle: .sajiloResources)
    static let aqiVeryUnhealthy = LocalizedStringResource("aqi.very-unhealthy", bundle: .sajiloResources)
    static let aqiHazardous = LocalizedStringResource("aqi.hazardous", bundle: .sajiloResources)
    static let aqiAdviceGood = LocalizedStringResource("aqi.advice.good", bundle: .sajiloResources)
    static let aqiAdviceModerate = LocalizedStringResource("aqi.advice.moderate", bundle: .sajiloResources)
    static let aqiAdviceSensitive = LocalizedStringResource("aqi.advice.sensitive", bundle: .sajiloResources)
    static let aqiAdviceUnhealthy = LocalizedStringResource("aqi.advice.unhealthy", bundle: .sajiloResources)
    static let aqiAdviceVeryUnhealthy = LocalizedStringResource("aqi.advice.very-unhealthy", bundle: .sajiloResources)
    static let aqiAdviceHazardous = LocalizedStringResource("aqi.advice.hazardous", bundle: .sajiloResources)
    static let airQuality = LocalizedStringResource("aqi.title", bundle: .sajiloResources)
    static let pm25 = LocalizedStringResource("aqi.pm25", bundle: .sajiloResources)
    static let pm10 = LocalizedStringResource("aqi.pm10", bundle: .sajiloResources)
    static let city = LocalizedStringResource("settings.city", bundle: .sajiloResources)
    static let reminders = LocalizedStringResource("settings.reminders", bundle: .sajiloResources)
    static let data = LocalizedStringResource("settings.data", bundle: .sajiloResources)
    static let openSettings = LocalizedStringResource("accessibility.open-settings", bundle: .sajiloResources)
    static let backToDashboard = LocalizedStringResource("accessibility.back-dashboard", bundle: .sajiloResources)
    static let publicHoliday = LocalizedStringResource("calendar.public-holiday", bundle: .sajiloResources)
    static let upcoming = LocalizedStringResource("screen.upcoming", bundle: .sajiloResources)
    static let dateConverter = LocalizedStringResource("screen.date-converter", bundle: .sajiloResources)
    static let dateDetails = LocalizedStringResource("screen.date-details", bundle: .sajiloResources)
    static let refresh = LocalizedStringResource("action.refresh", bundle: .sajiloResources)
    static let exchangeRates = LocalizedStringResource("screen.exchange-rates", bundle: .sajiloResources)
    static let general = LocalizedStringResource("settings.general", bundle: .sajiloResources)
    static let launchAtLogin = LocalizedStringResource("settings.launch-at-login", bundle: .sajiloResources)
    static let showDockIcon = LocalizedStringResource("settings.show-dock-icon", bundle: .sajiloResources)
    static let menuBar = LocalizedStringResource("settings.menu-bar", bundle: .sajiloResources)
    static let menuBarCustom = LocalizedStringResource("settings.menu-bar-custom", bundle: .sajiloResources)
    static let menuBarShowFlag = LocalizedStringResource("settings.menu-bar-show-flag", bundle: .sajiloResources)
    static let menuBarShowYear = LocalizedStringResource("settings.menu-bar-show-year", bundle: .sajiloResources)
    static let modules = LocalizedStringResource("settings.modules", bundle: .sajiloResources)
    static let weatherLocation = LocalizedStringResource("settings.weather-location", bundle: .sajiloResources)
    static let forexFavourites = LocalizedStringResource("settings.forex-favourites", bundle: .sajiloResources)
    static let weatherSource = LocalizedStringResource("settings.weather-source", bundle: .sajiloResources)
    static let ratesSource = LocalizedStringResource("settings.rates-source", bundle: .sajiloResources)
    static let festivalSource = LocalizedStringResource("settings.festival-source", bundle: .sajiloResources)
    static let calendarRange = LocalizedStringResource("settings.calendar-range", bundle: .sajiloResources)
    static let festivalsRange = LocalizedStringResource("settings.festivals-range", bundle: .sajiloResources)
    static let holidayTomorrow = LocalizedStringResource("reminder.holiday-tomorrow", bundle: .sajiloResources)
    static let festivalTomorrow = LocalizedStringResource("reminder.festival-tomorrow", bundle: .sajiloResources)
    static let today = LocalizedStringResource("action.today", bundle: .sajiloResources)
    static let swap = LocalizedStringResource("action.swap", bundle: .sajiloResources)
    static let copyAs = LocalizedStringResource("action.copy-as", bundle: .sajiloResources)
    static let previousMonth = LocalizedStringResource("calendar.previous-month", bundle: .sajiloResources)
    static let nextMonth = LocalizedStringResource("calendar.next-month", bundle: .sajiloResources)
    static let jumpToToday = LocalizedStringResource("calendar.jump-to-today", bundle: .sajiloResources)
    static let provisional = LocalizedStringResource("calendar.provisional", bundle: .sajiloResources)
    static let noEventToday = LocalizedStringResource("calendar.no-event", bundle: .sajiloResources)
    static let outOfRange = LocalizedStringResource("calendar.out-of-range", bundle: .sajiloResources)
    static let noUpcoming = LocalizedStringResource("upcoming.empty", bundle: .sajiloResources)
    static let allCurrencies = LocalizedStringResource("forex.all-currencies", bundle: .sajiloResources)
    static let favourites = LocalizedStringResource("forex.favourites", bundle: .sajiloResources)
    static let tomorrow = LocalizedStringResource("weather.tomorrow", bundle: .sajiloResources)
    static let numeralsDevanagari = LocalizedStringResource("numerals.devanagari", bundle: .sajiloResources)
    static let numeralsLatin = LocalizedStringResource("numerals.latin", bundle: .sajiloResources)
    static let reminderOffNote = LocalizedStringResource("settings.reminder-off-note", bundle: .sajiloResources)
    static let reminderDeniedNote = LocalizedStringResource("settings.reminder-denied-note", bundle: .sajiloResources)
    static let reminderPermissionNote = LocalizedStringResource("settings.reminder-permission-note", bundle: .sajiloResources)
    static let reminderEnabledNote = LocalizedStringResource("settings.reminder-enabled-note", bundle: .sajiloResources)
    static let launchApprovalNote = LocalizedStringResource("settings.launch-approval-note", bundle: .sajiloResources)
    static let launchUnavailableNote = LocalizedStringResource("settings.launch-unavailable-note", bundle: .sajiloResources)
    static let updates = LocalizedStringResource("settings.updates", bundle: .sajiloResources)
    static let checkForUpdates = LocalizedStringResource("action.check-for-updates", bundle: .sajiloResources)
    static let cancel = LocalizedStringResource("action.cancel", bundle: .sajiloResources)
    static let dayPlan = LocalizedStringResource("planner.title", bundle: .sajiloResources)
    static let addPlan = LocalizedStringResource("planner.add", bundle: .sajiloResources)
    static let noPlans = LocalizedStringResource("planner.empty", bundle: .sajiloResources)
    static let hasPlan = LocalizedStringResource("planner.has-plan", bundle: .sajiloResources)
    static let editPlan = LocalizedStringResource("planner.edit", bundle: .sajiloResources)
    static let deletePlan = LocalizedStringResource("planner.delete", bundle: .sajiloResources)
    static let savePlan = LocalizedStringResource("planner.save", bundle: .sajiloResources)
    static let planTitle = LocalizedStringResource("planner.title-field", bundle: .sajiloResources)
    static let planNote = LocalizedStringResource("planner.note-field", bundle: .sajiloResources)
    static let includeTime = LocalizedStringResource("planner.include-time", bundle: .sajiloResources)
    static let time = LocalizedStringResource("planner.time", bundle: .sajiloResources)
    static let reminder = LocalizedStringResource("planner.reminder", bundle: .sajiloResources)
    static let noReminder = LocalizedStringResource("planner.no-reminder", bundle: .sajiloResources)
    static let reminderAtTime = LocalizedStringResource("planner.reminder.at-time", bundle: .sajiloResources)
    static let reminderFiveMinutes = LocalizedStringResource("planner.reminder.five-minutes", bundle: .sajiloResources)
    static let reminderTenMinutes = LocalizedStringResource("planner.reminder.ten-minutes", bundle: .sajiloResources)
    static let reminderFifteenMinutes = LocalizedStringResource("planner.reminder.fifteen-minutes", bundle: .sajiloResources)
    static let reminderThirtyMinutes = LocalizedStringResource("planner.reminder.thirty-minutes", bundle: .sajiloResources)
    static let reminderOneHour = LocalizedStringResource("planner.reminder.one-hour", bundle: .sajiloResources)
    static let upNext = LocalizedStringResource("planner.up-next", bundle: .sajiloResources)
}
